# vim: ft=ansible:et:ts=2

- name: Update rs_collector configuration
  template:
    src: "etc/rs-collector.conf.j2"
    dest: '{{ _rs_collector.config_file | default("/etc/rs-collector.conf") }}'
    mode: 0640
    owner: root
    group: root

- name: Conigure OOM Score SystemD
  when: _rs_collector.oom_score_adj is defined
  block:
    - name: Check if SystemD Unit file for rs-collector exists
      stat:
        path: /etc/systemd/system/rs-collector.service
      register: stat_rs_collector_systemd

    - name: Set oom score for rs-collector in systemd
      lineinfile:
        dest: "/etc/systemd/system/rs-collector.service"
        state: present
        regexp: '^OOMScoreAdjust='
        line: "OOMScoreAdjust={{ _rs_collector.oom_score_adj }}"
        insertafter: '^\[Service\]'
      register: systemd_reload
      when: stat_rs_collector_systemd.stat.exists

    - name: Reload service definitions
      systemd:
        daemon_reload: yes
      when: systemd_reload.changed
