# vim: ft=ansible:et:ts=2

- name: Update rs_collector configuration
  template: src="etc/rs-collector.conf.j2" dest="{{ _rs_collector.config_file|default("/etc/rs-collector.conf") }}" mode="0640" owner=root group=root

- name: Check if init (override) file for rs-collector exists
  stat:
    path: /etc/init/rs-collector.override
  register: stat_rs_collector_override
  when: _rs_collector.oom_score is defined

- name: Set oom score for rs-collector
  lineinfile: dest="{{ stat_rs_collector_override.stat.path }}" state=present regexp='^oom score' line="oom score {{ _rs_collector.oom_score }}"
  when: _rs_collector.oom_score is defined and stat_rs_collector_override.stat.exists
